Misc improvements and unit tests
endlessm/merge-o-matic pull request #1
Opened 2018-07-27 12:27 UTC by dsd

https://phabricator.endlessm.com/T23401

2018-08-16 20:01 UTC, dbnicholson requested changes
Although I glossed over many of the details, this looks great! I just had a few minor issues I found, but otherwise it seems like you put a lot of effort into having this work correctly.

2018-08-16 20:01 UTC, dbnicholson commented on tests/__init__.py
> +    logging.basicConfig(level=logging.DEBUG)
You may want to have this fall back to `logging.INFO` if `MOM_TEST_DEBUG` is not set. Although, maybe you want the default of `logging.WARNING` so that it's basically silent in normal testing?

2018-08-16 20:01 UTC, dbnicholson commented on tests/produceMergesTests.py
> +    self.assertTrue(upstream > pkg_version)
You can use `assertGreater(upstream, pkg_version)` to get a more helpful error out if the test fails.

2018-08-16 20:01 UTC, dbnicholson commented on model/base.py
> +import apt_pkg
This may not be totally necessary but at least in the past it was necessary to initializes the underlying `libapt-pkg.so` by calling `apt_pkg.init()` before working with it.

2018-08-16 20:01 UTC, dbnicholson commented on model/base.py
> +    file_match = '*_%s_%s_source_Sources' % (dist, component)
I think this is pretty safe. The way this is actually constructed in apt is the internal `URItoFileName` function - https://salsa.debian.org/apt-team/apt/blob/master/apt-pkg/contrib/strutl.cc#L504. Essentially, it strips the scheme and any embedded auth details and then converts `/` to `_`.

2018-08-16 20:01 UTC, dbnicholson commented on model/base.py
> +      self.data = json.load(open(self.path, 'r'))
Although the file will eventually be closed, I think it's best to be explicit about it to reduce the number of concurrently open files using a context manager:
```
with open(self.path, 'r') as f:
    self.data = json.load(f)
```

2018-08-16 20:01 UTC, dbnicholson commented on model/base.py
> +    json.dump(self.data, open(self.path, 'w'))
Same thing about using the `with open()` context manager.

2018-08-16 20:01 UTC, dbnicholson commented on deb/version.py
> +        self.epoch = None
A useful cleanup would be to drop this class entirely and just use `debian.debian_support.Version` from python-debian. I checked and it handles an epoch of 0 correctly.

2018-08-17 03:14 UTC, dsd commented
Thanks. I made the suggested changes, rebased and pushed, except for reworking the Version stuff (will do that another time, and potentially also use python-debian's control file parser too).

2018-08-17 03:14 UTC, closed without merging